In [ ]:
!python --version

Python 3.13.16

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

with open('/content/drive/My Drive/data.txt', 'w') as f:
    f.write('Шкідники картоплі:\n')
    f.write('1. Колорадський жук\n')
    f.write('2. Попелиця\n')
    f.write('3. Картопляна міль\n')

print("Вміст файлу data.txt:")
!cat /content/drive/My\ Drive/data.txt

Mounted at /content/drive
Вміст файлу data.txt:
Шкідники картоплі:
1. Колорадський жук
2. Попелиця
3. Картопляна міль

In [ ]:
import pandas as pd

csv_data = """pest_id,pest_name,avg_length_mm,color,damage_type
1,Colorado potato beetle,10.0,Yellow-black stripes,Leaf defoliation
2,Potato Aphid,2.5,Green-pink,Sap sucking and curling
3,Potato Tuber Moth,10.0,Gray-brown,Tuber and leaf mining
4,Wireworm,20.0,Yellow-brown,Root and tuber boring
"""

with open('/content/drive/My Drive/pests_data.csv', 'w') as f:
    f.write(csv_data)

file_path = '/content/drive/MyDrive/pests_data.csv'
df = pd.read_csv(file_path)

print("Перші рядки датасету")
display(df.head())

print("\nСтатистичні характеристики")
display(df.describe())

print("\nІнформація про датасет та відсутні значення")
df.info()

Перші рядки датасету

,pest_id,pest_name,avg_length_mm,color,damage_type
0,1,Colorado potato beetle,10.0,Yellow-black stripes,Leaf defoliation
1,2,Potato Aphid,2.5,Green-pink,Sap sucking and curling
2,3,Potato Tuber Moth,10.0,Gray-brown,Tuber and leaf mining
3,4,Wireworm,20.0,Yellow-brown,Root and tuber boring

Статистичні характеристики

        pest_id  avg_length_mm
count  4.000000       4.000000
mean   2.500000      10.625000
std    1.290994       7.180703
min    1.000000       2.500000
25%    1.750000       8.125000
50%    2.500000      10.000000
75%    3.250000      12.500000
max    4.000000      20.000000

Інформація про датасет та відсутні значення
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pest_id        4 non-null      int64
 1   pest_name      4 non-null      object
 2   avg_length_mm  4 non-null      float64
 3   color          4 non-null      object
 4   damage_type    4 non-null      object
dtypes: float64(1), int64(1), object(3)
memory usage: 292.0+ bytes

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Input(shape=(150, 150, 3)),
    layers.Rescaling(1./255),

    layers.Conv2D(32, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),

    layers.Dense(64, activation='relu'),
    layers.Dense(4, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ rescaling (Rescaling)           │ (None, 150, 150, 3)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d (Conv2D)                 │ (None, 148, 148, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 74, 74, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 72, 72, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 36, 36, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 34, 34, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 73984)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 64)             │     4,735,040 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │           260 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 4,791,620 (18.28 MB)

 Trainable params: 4,791,620 (18.28 MB)

 Non-trainable params: 0 (0.00 B)